theme: jekyll-theme-minimal
title: Amruta Jadhav
description: Graduate Student in the Information Management Program at University of Washington, Seattle. I am specializing in data science.
logo: /images/ppic.jpg